### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by itslukej** [maxerbox/vscode-discord#1]
🙏

**Comment by minemidnight** [comment]
:pray:

**Comment by bjxke** [comment]
🙏

**Comment by julien777z** [comment]
🙏

**Comment by maxerbox** [comment]
Well, I need your help, I need to deal with discord-rpc native code.
I'm not working on a Osx environment, it's hard.
See https://github.com/discordapp/discord-rpc/blob/master/src/discord_register_osx.m

**Comment by fratik** [comment]
@maxerbox I'm on Osx now, but I don't have any experience in C (C, C#, C++, etc) 😛

**Comment by fratik** [comment]
But idk if this needs a kind of registery. Works well without. 
<img width="186" alt="Rich Presence" src="https://user-images.githubusercontent.com/28189051/33097565-e817f77c-cf0a-11e7-9cd1-9893c3bc5d65.png">

**Comment by ghost** [comment]
🙏

**Comment by coadler** [comment]
🙏

**Comment by aidabeorn** [comment]
@Fratik Most likely not needed, Linux didn't need anything like it.

**Comment by coadler** [comment]
mac support!!
![hahaa](https://cdn.discordapp.com/attachments/283356472258199552/382787987064487936/unknown.png)

**Comment by itslukej** [comment]
god bless 🙏
