### ISSUE TITLE
not working on insiders?

### ISSUE THREAD

**Issue by lewisakura** [maxerbox/vscode-discord#11]
trying to install extension doesn't work on insiders edition of VSC. just reports an error about there not being a version available.

**Comment by maxerbox** [comment]
Hmmm, interesting, it's maybe the package.js version compatibility field, I'm gonna check that. What's your vscode insider version ?

**Comment by lewisakura** [comment]
It seems to have started working now, looks like Insiders was bugging out. It was 1.10, which was the incorrect version.

**Comment by Xalaxis** [comment]
Just reporting here the last version I ran worked fine on insiders.

**Comment by maxerbox** [comment]
@LewisTehMinerz your insider version wasn't up to date ^^. The current LTS release is 1.18
