### ISSUE TITLE
Is there a way we can select the image that appears?

### ISSUE THREAD

**Issue by fourjr** [maxerbox/vscode-discord#12]
Instead of based on the language and the VS Code icon, can we select our own images?

**Comment by aidabeorn** [comment]
You can register your own app and enable rich presence @ https://discordapp.com/developers/applications/me, then set discord.clientID in your user settings to your new app.

**Comment by fourjr** [comment]
so the rich presence on our account would be the avatar of that app? or what? sorry if im not getting you

**Comment by maxerbox** [comment]
Indeed, the image (also called assets) need to be uploaded manually by the application's owner (more informations [here](https://discordapp.com/developers/docs/rich-presence/how-to#your-new-developer-dashboard). So, basycally you can create a new developer app, enable Rich Presence,  add assets, copy past the clientID in the discord.clientID field as @thorerik said. You can edit the discord.iconMap to change the asset name for each file extension.

**Comment by fourjr** [comment]
Oh yes, thank you! I'll test it out later when I get back home but from what I see on the app creation screen, pretty sure I know what I'm doing!

**Comment by fourjr** [comment]
@maxerbox what is the default image if a image cant be found in the iconMap? Tried `vscode` but it didn't work

**Comment by maxerbox** [comment]
Indeed, that's `vscode`

2017-11-24 16:22 GMT+01:00 fourjr <notifications@github.com>:
