### ISSUE TITLE
Storing stuff in registry... why?

### ISSUE THREAD

**Issue by MrJacz** [maxerbox/vscode-discord#15]
title ^

**Comment by maxerbox** [comment]
VSCode has to be registered for some features, refering to the official discord-rpc sdk https://github.com/discordapp/discord-rpc/blob/master/src/discord_register_win.cpp#L49

**Comment by tjreigh** [comment]
Then explain why [iCrawl's package](https://github.com/iCrawl/discord-vscode) achieved exactly the same functionality without ever touching the registry?
This package is sketchy. You are sketchy.

**Comment by TJDoesCode** [comment]
So why can [iCrawl's package](https://github.com/iCrawl/discord-vscode) achieve the same functionality without touching the registry?
This package is sketchy. You are sketchy.
And you appear to have deleted my previous comment. Anything you're trying to cover up, my dude?

**Comment by lewisakura** [comment]
using the registry is not needed when using rich presence. please stop doing it. as stated above, it makes the package look sketchy. a VSC package should never need to touch the registry, ever.

**Comment by samcadams** [comment]
To be fair, He just migrated the code from Discord's RPC repo, which if you looked at the link he included, it edits the registry.

It isn't really "sketchy", its more of just pointlessly adding something that as far as I can see has no real use in the program.

Not his fault /shrug

**Comment by MrJacz** [comment]
There is no real reason (it is not needed...) to be adding random shit to your computer's registry I mean No point at all it makes this extension look sketchy and people use Crawls extension.

**Comment by maxerbox** [comment]
@TJDoesCode @LewisTehMinerz @MrJacz @Fires1 

> By committing to an RPC-only integration, you decide to forego the work our library and header file have done for you in the way of error handling, state storage, disconnecting and reconnecting, and other quality of life abstractions. While simply implementing the new RPC command and events will enable Rich Presence for your game, we highly suggest that you do your best to mimic the functionality of the SDK the most that you can. It ensure not only code quality on your part, but also an excellent experience on the part of your players.

> One thing that cannot be explicitly done over RPC is registering an application protocol for your game. If you choose to do an RPC-only implementation, you will have to register your application protocol yourself in the format of discord-[your_app_id]://. You can use Discord_Register() as a good(?) example of how to properly register an application protocol for use with Discord. For OSX and Linux it is probably simpler to handle the protocol registration as part of your install/packaging.

I have followed the Rich Presence documentation, as intented. It says that when you use the discord-dpc server, you need to manually register the app.

https://github.com/discordapp/discord-rpc/blob/master/documentation/hard-mode.md#hark-a-warning.

The Discord Registering function got removed anyway in the 1.0.0 release.
Check out https://github.com/maxerbox/vscode-discord/commit/826f0160ced9abdcdb7c3809d3a88633088abbb3#diff-06f1274e40de25abda72d812b1cce86aR23

**Comment by lewisakura** [comment]
> registering an application protocol for your game

this isn't needed if you're doing simple rich presence. anyway, thank you for removing registry editing.

**Comment by Bluexin** [comment]
Adding further onto this, the registries thingie is used in discord-rpc to automatically launch the game when oyu press "join" or "spectate", that's all.
Besides, by reading the code you can see it's nothing really sketchy (apart from the fact windub registries are sketchy to begin with).
