### ISSUE TITLE
Showing "Idle" while editing C files

### ISSUE THREAD

**Issue by COLAMAroro** [maxerbox/vscode-discord#22]
Pretty explanatory

While workings on school projects, it looks like editing C file is considered as Idling
![2017-12-09-145553_1920x1080_scrot](https://user-images.githubusercontent.com/12484955/33796270-32406e8a-dcf1-11e7-80a2-ba69a46b0a79.png)
Tho, working on others file types shows no issue
![2017-12-09-145811_1920x1080_scrot](https://user-images.githubusercontent.com/12484955/33796280-6508051c-dcf1-11e7-99e8-e5e2a87165d0.png)

Using Discord Canary on Fedora 26

**Comment by Zyrophr** [comment]
Same thing here.
All of my .c projects are showing as "Idling" for Discord.
Works really good with every other language I tried 👍 

Also, when switching to a working file (like settings.json) , when I go back to my C project it shows that I'm always editing my settings !

![2017-12-09-150226_1920x1080_scrot](https://user-images.githubusercontent.com/31597162/33796316-1e5f416a-dcf2-11e7-8850-f24c22621425.png)
