### ISSUE TITLE
Regarding RPC Usage

### ISSUE THREAD

**Issue by robflop** [maxerbox/vscode-discord#3]
Does Discord permit usage of RPC like this?

I'm not too knowledgeable on the subject, but as far as I know, RPC is only for games and so on.
Have you checked whether usage through a non-game such as an extension for an editor like this is permitted?

Thanks.

**Comment by Xalaxis** [comment]
Discord refers to 'apps' in the documentation [here](https://discordapp.com/developers/docs/topics/rpc#private-beta-fyi) which would suggest it is designed for all types of application.  Perhaps the bigger issue is whether permission is needed to use the RPC at all which is what the docs seem to imply.

**Comment by robflop** [comment]
@Xalaxis Thanks for the info! I'll read up on some of it myself aswell while I wait for more from others (e.g. maxerbox)

**Comment by maxerbox** [comment]
Indeed, it is poor documented about the Rich Presence use. More will come, I guess, as it is a new feature.
For now, the only restricted thing is about the "Spectacle" & "Join" buttons, [which need to be aproved from the discord team.](https://discordapp.com/developers/docs/rich-presence/getting-approved) 

Like that quote says, from the [Rich Presence FAQ:](https://discordapp.com/developers/docs/rich-presence/faq#q-can-i-change-something-in-the-sdk-for-my-own-purposes?)

>  Q: Can I change something in the SDK for my own purposes?
> Go nuts! The SDK is open source by design. If you need or want to change something for the purposes of your specific integration—like changing our JSON parser, or changing all of the variable names to the names of your pets—go ahead and tinker to your heart's content.

It seems to be very "open" from use.

In the other hand, the Rich Presence is dedicated for "Games". I'm gonna email the Discord team about it.

**Comment by robflop** [comment]
Thank you. Please let me know the news once they reply!

**Comment by fratik** [comment]
It is permitted. I've asked on [Discord Testers](http://discord.gg/discord-testers) yesterday. I don't know if making this an extension for VSCode is permitted but, the same idea is fine. 

<img width="844" alt="Source" src="https://user-images.githubusercontent.com/28189051/33094933-2342f850-cf02-11e7-9687-3328197a90f6.png">

**Comment by maxerbox** [comment]
So I've contacted them:

> Dear Discord Team
> 
> With the new Rich Presence feature, it opened new ways to show the things you areing.
> I have developed a "Visual Studio Code" extension which allow to display your current project you are working on, the file you are editing etc....
> 
>  I was wondering if such a thing is approved, since it is not related to "Games".
> 
> Regards, Simon Sassi.

Their response:
![response](https://i.imgur.com/b3UQzPD.png)

Well it's totally fine!
