### ISSUE TITLE
Can't connect to RPC, if Discord is installed as a snap

### ISSUE THREAD

**Issue by n0toose** [maxerbox/vscode-discord#33]
I had to start working to a different workplace running on Debian a few days ago, so, for the sake of convenience, I installed Discord as a snap. In my setup, Visual Studio Code has also been installed as a snap.

The snap itself is distributed by the [Snapcrafters team](https://snapcraft.io/install/discord/debian).

Here's the error that shows up:
`Can't connect to discord rpc: connect ENOENT /run/user/1000/snap.code/discord-ipc-0`

**Comment by shuashock** [comment]
^same

**Comment by maxerbox** [comment]
See https://github.com/maxerbox/vscode-discord/issues/26#issuecomment-424079433
