### ISSUE TITLE
Discord-rpc:child error message

### ISSUE THREAD

**Issue by jnoc** [maxerbox/vscode-discord#34]
![image](https://user-images.githubusercontent.com/30672425/82733114-99debf80-9d09-11ea-931a-c0038d58647d.png)

`Discord-rpc:child "activity" fails because [child "assets" fails because [child "large_text" fails because ["large_text" length must be at least 2 characters long]]]`

**Comment by jnoc** [comment]
![image](https://user-images.githubusercontent.com/30672425/82733138-d4e0f300-9d09-11ea-8613-52f4fc6d946b.png)

Rich presence works as intended even with error message constantly popping up in VSCode

**Comment by maxerbox** [comment]
> ![image](https://user-images.githubusercontent.com/30672425/82733138-d4e0f300-9d09-11ea-8613-52f4fc6d946b.png)
> 
> Rich presence works as intended even with error message constantly popping up in VSCode

Hum, it's been a long since I didn't update deps, maybe discord changed a little bit their ipc interface
