### ISSUE TITLE
import name

### ISSUE THREAD

**Issue by violet-sys** [maxerbox/vscode-discord#35]
whats the name i put in for it to import- im sorry i forgot
i tried `import vscode-discord` and discord was an invalid syntax?? i also tried `import discord-vscode` but vscode was an invalid syntax-

**Comment by maxerbox** [comment]
Hmmm, what do you mean by import ?
Which language are you using ?

**Comment by violet-sys** [comment]
> Hmmm, what do you mean by import ?
> Which language are you using ?

python

**Comment by maxerbox** [comment]
> > Hmmm, what do you mean by import ?
> > Which language are you using ?
> 
> python

Oh, I see ! 
Sorry, you are at the wrong place !
This is a Visual Studio Code extension. You need to install it on vscode.

If you would like to talk with discord rich presence, you should look into this package https://github.com/qwertyquerty/pypresence
It will allows to do the same thing as this extension.

I close this issue, but feel free to comment below
